services:
  oidc:
    container_name: oidc
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    hostname: oidc
    ports:
      - 8080:8080
    env_file:
      - ./mock/oidc.env
    volumes:
      - ./mock/oidc.config.json:/opt/oidc.config.json